/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DistributorsRouteImport } from './routes/distributors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsPreetiRouteImport } from './routes/brands.preeti'
import { Route as BrandsGoodMorningIndiaRouteImport } from './routes/brands.good-morning-india'

const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorsRoute = DistributorsRouteImport.update({
  id: '/distributors',
  path: '/distributors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsPreetiRoute = BrandsPreetiRouteImport.update({
  id: '/brands/preeti',
  path: '/brands/preeti',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsGoodMorningIndiaRoute = BrandsGoodMorningIndiaRouteImport.update({
  id: '/brands/good-morning-india',
  path: '/brands/good-morning-india',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distributors': typeof DistributorsRoute
  '/gallery': typeof GalleryRoute
  '/process': typeof ProcessRoute
  '/brands/good-morning-india': typeof BrandsGoodMorningIndiaRoute
  '/brands/preeti': typeof BrandsPreetiRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distributors': typeof DistributorsRoute
  '/gallery': typeof GalleryRoute
  '/process': typeof ProcessRoute
  '/brands/good-morning-india': typeof BrandsGoodMorningIndiaRoute
  '/brands/preeti': typeof BrandsPreetiRoute
  '/brands': typeof BrandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distributors': typeof DistributorsRoute
  '/gallery': typeof GalleryRoute
  '/process': typeof ProcessRoute
  '/brands/good-morning-india': typeof BrandsGoodMorningIndiaRoute
  '/brands/preeti': typeof BrandsPreetiRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/distributors'
    | '/gallery'
    | '/process'
    | '/brands/good-morning-india'
    | '/brands/preeti'
    | '/brands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/distributors'
    | '/gallery'
    | '/process'
    | '/brands/good-morning-india'
    | '/brands/preeti'
    | '/brands'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/distributors'
    | '/gallery'
    | '/process'
    | '/brands/good-morning-india'
    | '/brands/preeti'
    | '/brands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DistributorsRoute: typeof DistributorsRoute
  GalleryRoute: typeof GalleryRoute
  ProcessRoute: typeof ProcessRoute
  BrandsGoodMorningIndiaRoute: typeof BrandsGoodMorningIndiaRoute
  BrandsPreetiRoute: typeof BrandsPreetiRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributors': {
      id: '/distributors'
      path: '/distributors'
      fullPath: '/distributors'
      preLoaderRoute: typeof DistributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/preeti': {
      id: '/brands/preeti'
      path: '/brands/preeti'
      fullPath: '/brands/preeti'
      preLoaderRoute: typeof BrandsPreetiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/good-morning-india': {
      id: '/brands/good-morning-india'
      path: '/brands/good-morning-india'
      fullPath: '/brands/good-morning-india'
      preLoaderRoute: typeof BrandsGoodMorningIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DistributorsRoute: DistributorsRoute,
  GalleryRoute: GalleryRoute,
  ProcessRoute: ProcessRoute,
  BrandsGoodMorningIndiaRoute: BrandsGoodMorningIndiaRoute,
  BrandsPreetiRoute: BrandsPreetiRoute,
  BrandsIndexRoute: BrandsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
